name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test aws-cdk
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Test cdk synth using the latest version
        uses: ./
        with:
          cdk_subcommand: "synth"
          cdk_version: "1.16.2"
          cdk_stack: "TestStack"
          working_dir: "test"
      - name: Test cdk synth using 1.16.2
        uses: ./
        with:
          cdk_subcommand: "synth"
          cdk_version: "1.16.2"
          cdk_stack: "TestStack"
          working_dir: "test"
